config/routes.rb
ListMaker::Application.routes.draw do
  resources :lists, :tasks
  

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name
  
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :task_name, :list_id, :status
  
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
respond_to :html, :json

    def show
      @list = List.find(params[:id])
      respond_with(@list)
    end

    def index
      @lists = List.all
      respond_with(@lists)
    end

    def new
      @list = List.new
      respond_with(@list)
    end

    def create
      @list = List.new(params[:list])
      # @list.name = (params[:list][:name])
      @list.save      
      
      # tasks_array = (params[:list][:tasks].split("; "))
      # tasks_array.each do |task|
      #   new_task = Task.new
      #   new_task.task_name = task
      #   new_task.list_id = @list.id
      #   new_task.status = 0
      #   new_task.save
      # end

      respond_with @list
    end

    def edit
      @list = List.find(params[:id])
      respond_with(@list)
    end

    def update
      @list = List.find(params[:id])
      @list.update_attributes(params[:list])
        
      respond_with do |format|
        format.html do
          if @list.save
            redirect_to task_url(@list)
          else
            render 'edit'
          end
        end

        format.json do
          if @list.save
            render :json => @list
          else
            render :json => @list.errors
          end
        end
      end
    end
    

    def destroy
      @list = List.find(params[:id])
      @list.destroy
      respond_with @list, :location => lists_path
    end

  end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
respond_to :html, :json

  def show
    @task = Task.find(params[:id])
    respond_with(@task)
  end
  
  def index
    @tasks = Task.all
    # where( list_id: params[:list_id] )
    respond_with(@tasks)
  end
  
  def new
    @task = Task.new
    @lists = List.all
    respond_with(@task)
  end

  def create
    @task = Task.new(params[:task])      
    
    # respond_with @task
    
    respond_with do |format|
      format.html do
        if @task.save
          redirect_to task_url(@task)
        else
          render 'new'
        end
      end
      
      format.json do
        if @task.save
          render :json => @task
        else
          render :json => @task.errors
        end
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
    respond_with(@task)
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(params[:task])
    # respond_with @task
    
    respond_with do |format|
      format.html do
        if @task.save
          redirect_to task_url(@task)
        else
          render 'edit'
        end
      end
      
      format.json do
        if @task.save
          render :json => @task
        else
          render :json => @task.errors
        end
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_with @task, :location => lists_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ListMaker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/edit.html.erb
<h1>Edit your <%= @list.name %> list:</h1>

<%= form_for(@list) do |f| %>

	<%= f.label :name, "Rename your list:" %>
	<%= f.text_field :name %>
	
	<%= f.submit "Save changes!" %>

<% end %>

<%= link_to "Delete Entire List", @list, method: :delete, data: { confirm: "You sure?" } %>

app/views/lists/index.html.erb
<h1>All the lists you've made:</h1>

<% @lists.each do |list| %>
	<h2><%= link_to "#{list.name.capitalize}", list_path(list) %></h2>

	<% list.tasks.each do |task| %>
		<ul><li><%= link_to "#{task.task_name.capitalize}", task_path(task) %></li></ul>
	<% end%>
	
<% end %>

<%= link_to "Create a new list", new_list_path %>

app/views/lists/new.html.erb
<h1>Create a new list here!</h1>

<%= form_for(@list) do |f| %>

	<%= f.label :name, "Name your list:" %>
	<%= f.text_field :name %>
	
	<%#=f.label :tasks, "Task separated by semi-colon + space:" %>
	<%#=f.text_field :tasks %>
	
	<%= f.submit "Create List!" %>

<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name.capitalize %></h1>
The list ID number of this list is: <%= @list.id %>

<% @list.tasks.each do |task| %>
	<ul><li>
		<%= task.task_name.capitalize %>......................                               
		<%= link_to "Edit", edit_task_path(task) %>
	</li></ul>
<% end%>

<%= link_to "Edit the list", edit_list_path %>
<%= link_to "Add a task", new_task_path %>

app/views/tasks/edit.html.erb
<h1>Edit your <%= @task.task_name %> task within the <%= @task.list.name %> list:</h1>

<%= form_for(@task) do |f| %>

	<%= f.label :task_name, "Rename your task:" %>
	<%= f.text_field :task_name %>
	<br>
	<%= f.label :status, "What is the status of this task? 0=not done 1=done" %>
	<%= f.text_field :status %>
	<br>
	<%= f.submit "Save changes!" %>

<% end %>

<br>
<%= link_to "Delete Task", @task, method: :delete, data: { confirm: "You sure?" } %>

app/views/tasks/index.html.erb
<h1>All the tasks in your lists:</h1>
<%# lookup_id = (params[:list_id]).to_i %>
<% @tasks.each do |task|%>

	<li><%= link_to "#{task.task_name}", task_path(task) %></li>
	
<% end %>

<%= link_to "Create a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Create a new task here!</h1>

<%= form_for(@task) do |f| %>

	<%= f.label :task_name, "Name your task:" %>
	<%= f.text_field :task_name %>
	<br>
	<%= f.label :list_id, "What is the list ID?" %>
	<%= f.text_field :list_id %>
	<br>
	<%= f.label :status, "What is the status of this task? (0=not done 1=done)" %>
	<%= f.text_field :status %>
	<br>
	<%= f.submit "Create List!" %>

<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.task_name.capitalize %></h1>

This task belongs to the <%= link_to "#{List.find(@task.list_id).name.capitalize} List", list_path(@task.list_id) %>
<br>
<br>
<%= link_to "Edit this task", edit_task_path %>